import { useState } from 'react';

export default function ReportExport({ results, videoMeta }) {
  const [exporting, setExporting] = useState(false);
  const [exportStatus, setExportStatus] = useState(null);

  if (!results) return null;

  const generateMarkdown = () => {
    const categories = results.categories?.join(', ') || 'N/A';
    const timestamp = new Date().toLocaleString();
    
    let md = `# Research Report: ${results.title || videoMeta?.title || 'Video Analysis'}\n\n`;
    md += `**Date:** ${timestamp}\n`;
    md += `**Categories:** ${categories}\n\n`;
    md += `## Summary\n${results.summary || 'No summary provided.'}\n\n`;

    if (results.steps?.length > 0) {
      md += `## Step-by-Step Instructions\n`;
      results.steps.forEach((step, i) => {
        md += `### ${i + 1}. ${step.title}\n`;
        if (step.detail) md += `${step.detail}\n`;
        if (step.timestamp) md += `*Timestamp: ${step.timestamp}*\n`;
        md += `\n`;
      });
    }

    if (results.books?.length > 0) {
      md += `## Books Mentioned\n`;
      results.books.forEach(book => {
        md += `- **${book.title}** by ${book.author}\n`;
        if (book.context) md += `  *Context: ${book.context}*\n`;
      });
      md += `\n`;
    }

    if (results.authors?.length > 0) {
      md += `## Experts & Authors\n`;
      results.authors.forEach(author => {
        md += `- **${author.name}**\n`;
        if (author.context) md += `  *${author.context}*\n`;
      });
      md += `\n`;
    }

    if (results.resources?.length > 0) {
      md += `## Additional Resources\n`;
      results.resources.forEach(res => {
        md += `- **${res.name}** (${res.type})\n`;
        if (res.context) md += `  *${res.context}*\n`;
      });
    }

    md += `\n---\n*Generated by Researcher AI*`;
    return md;
  };

  const handleDownload = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    const safeTitle = (results.title || 'report').toLowerCase().replace(/[^a-z0-9]/g, '-');
    a.href = url;
    a.download = `research-report-${safeTitle}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePushToDrive = async () => {
    setExporting(true);
    setExportStatus(null);
    try {
      const md = generateMarkdown();
      const safeTitle = (results.title || 'report').toLowerCase().replace(/[^a-z0-9]/g, '-');
      const filename = `report-${safeTitle}-${Date.now()}.md`;

      const res = await fetch('/api/export', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ filename, content: md }),
      });

      if (!res.ok) throw new Error('Failed to export to Drive');
      
      const data = await res.json();
      setExportStatus({ success: true, message: `Saved to Google Drive!` });
      setTimeout(() => setExportStatus(null), 3000);
    } catch (err) {
      setExportStatus({ success: false, message: err.message });
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="card card--accent export-controls">
      <div className="section-header">
        <div className="section-header__icon section-header__icon--emerald">📤</div>
        <div className="section-header__text">
          <h2>Export Report</h2>
          <p>Save analysis as a Markdown file</p>
        </div>
      </div>
      
      <div className="export-actions">
        <button className="url-input__btn export-btn" onClick={handleDownload}>
          💾 Download Markdown
        </button>
        <button 
          className="url-input__btn export-btn export-btn--drive" 
          onClick={handlePushToDrive}
          disabled={exporting}
        >
          {exporting ? '⏳ Pushing...' : '📁 Push to Google Drive'}
        </button>
      </div>

      {exportStatus && (
        <div className={`export-status export-status--${exportStatus.success ? 'success' : 'error'}`}>
          {exportStatus.success ? '✅' : '❌'} {exportStatus.message}
        </div>
      )}
    </div>
  );
}
